all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    es:
      hosts:
        elasticsearch:
          ansible_host: 10.0.0.4
          ansible_user: ansible
        kibana:
          ansible_host: 10.0.0.5
          ansible_user: ansible
        fleet:
          ansible_host: 10.0.0.6
          ansible_user: ansible
    infra:
      hosts:
        nginx:
          ansible_host: 10.0.0.2
          ansible_user: ansible
        pfsense:
          ansible_host: 192.168.254.1
          ansible_user: ansible
