---
- name: Initialise machine
  hosts: nginx
  become: true
  vars:
    become_pass: "{{ ansible_become_pass }}"
  tasks:
    - name: Ensure all necessary packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop: ["curl", "nginx"]
