---
- name: Initialise machine
  hosts: nginx
  become: true
  vars:
    become_pass: "{{ ansible_sudo_pw }}"
  tasks:
    - name: Ensure all necessary packages are installed
      apt:
        name: "{{ item }}"
        state: present
      when: ansible_os_family == "Debian"
      loop: ["curl", "nginx"]
