all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible
  hosts:
    localhost:
      ansible_connection: local
  children:
    es:
      hosts:
        es1:
          ansible_host: 10.0.100.4
        es2:
          ansible_host: 10.0.100.5
        es3:
          ansible_host: 10.0.100.6
        kibana:
          ansible_host: 10.0.100.4
        fleet:
          ansible_host: 10.0.100.3
    infra:
      hosts:
        nginx:
          ansible_host: 10.0.0.2
        pfsense:
          ansible_host: 192.168.254.1
