---
- name: Add Match rule to sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "Match Address 10.0.100.2"
    create: yes
    state: present

- name: Allow only specific user from that IP
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "  AllowUsers ansible"
    insertafter: "Match Address 10.0.100.2"

- name: Ensure SSH is running
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
  notify: Restart SSH
